Create aditro-submit-1.md
rian669/task pull request #1
Opened 2024-11-02 05:49 UTC by rianaditro

2024-11-02 05:53 UTC, rian669 requested changes
fix it

2024-11-02 05:53 UTC, rian669 commented on aditro-submit-1.md
> +Email: rianaditro@gmail.com.id
email is not valid

2024-11-02 05:53 UTC, rian669 commented on aditro-submit-1.md
> +Status: very handsome
this data is not needed

2024-11-02 05:59 UTC, rianaditro commented on aditro-submit-1.md
> +Status: very handsome
what it should be?

2024-11-02 05:59 UTC, rianaditro commented on aditro-submit-1.md
> +Email: rianaditro@gmail.com.id
ok. fixed it

2024-11-02 06:10 UTC, rianaditro reviewed
updated

2024-11-02 06:12 UTC, rian669 commented
ok

2024-11-02 06:12 UTC, closed without merging

2024-11-22 09:40 UTC, rian669 reviewed
ok